// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

// Problem RFC7807 Problem Details
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  *string `json:"traceId,omitempty"`
	Type     string  `json:"type"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`

	// ImageId ID of the product's main image
	ImageId  *string `json:"imageId,omitempty"`
	Name     string  `json:"name"`
	Price    float32 `json:"price"`
	Quantity int     `json:"quantity"`
}

// GetRandomProductsParams defines parameters for GetRandomProducts.
type GetRandomProductsParams struct {
	// Count Number of random products to retrieve (1-20)
	Count int `form:"count" json:"count"`
}
